blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: ğŸ’¡ ê¸°ëŠ¥ ì¶”ê°€ (Feature)
    description: ìƒˆë¡œìš´ ê¸°ëŠ¥ ìš”ì²­
    file: feat.yml

  - name: ğŸ ë²„ê·¸ ë¦¬í¬íŠ¸ (Bug)
    description: ì˜¤ë¥˜ë‚˜ ë¬¸ì œ ì œë³´
    file: bug.yml

  - name: ğŸ“ ë¬¸ì„œ ê´€ë ¨ (Docs)
    description: ë¬¸ì„œ, ì£¼ì„ ìš”ì²­
    file: docs.yml

  - name: ğŸ§¹ ë¦¬íŒ©í† ë§ ìš”ì²­ (Refactor)
    description: ì½”ë“œ êµ¬ì¡° ê°œì„  ìš”ì²­
    file: refactor.yml
